[package]
name = "service-health-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.11"
curl = "=0.4.46"
dotenv = "0.15.0"
csv = "1.3.0"
